version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "aws-osam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bugbg9vujy93"
s3_prefix = "aws-osam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
